if empty($XDG_CONFIG_HOME)
   let $XDG_CONFIG_HOME = expand('~/.config')
endif
if empty($XDG_CACHE_HOME)
   let $XDG_CACHE_HOME = expand('~/.cache')
endif
if empty($XDG_DATA_HOME)
   let $XDG_DATA_HOME = expand('~/.local/share')
endif

silent! call mkdir($XDG_CACHE_HOME . '/vim/swap', 'p', 0700)
silent! call mkdir($XDG_CACHE_HOME . '/vim/backup', 'p', 0700)
silent! call mkdir($XDG_CACHE_HOME . '/vim/undo', 'p', 0700)

set directory=$XDG_CACHE_HOME/vim/swap//,~/,/tmp/
set backupdir=$XDG_CACHE_HOME/vim/backup//,~/,/tmp/
set undodir=$XDG_CACHE_HOME/vim/undo//,~/,/tmp/
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set runtimepath+=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME
let $MYVIMRC = "$XDG_CONFIG_HOME/vim/vimrc"

set nocompatible
set laststatus=2 " Always show status line

if has("autocmd")
  au VimEnter,InsertLeave * silent execute '!echo -ne "\e[2 q"' | redraw!
  au InsertEnter,InsertChange *
    \ if v:insertmode == 'i' |
    \   silent execute '!echo -ne "\e[6 q"' | redraw! |
    \ elseif v:insertmode == 'r' |
    \   silent execute '!echo -ne "\e[4 q"' | redraw! |
    \ endif
  au VimLeave * silent execute '!echo -ne "\e[ q"' | redraw!
endif

if has("syntax")
  syntax on
endif " Enable syntax highlighting

set encoding=utf8 nobomb
set number " Show line numbers
set ruler
set relativenumber
set showmode " Show current mode
set showcmd " Show command in status line

set autoindent " Enable auto indentation"
set tabstop=4
set shiftwidth=4
set expandtab " Use spaces instead of tabs
set wildmenu " Enhanced command line completion

" Enable search settings
set incsearch " Incremental search
set ignorecase " Ignore case in search patterns
set smartcase " Override ignorecase if search pattern contains uppercase letters
set hlsearch " Highlight search results

set mouse=a " Enable mouse support

let mapleader=" "
map <F1> :help<CR>
nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader>wq :wq<CR>
nnoremap <leader>r :source $XDG_CONFIG_HOME/vim/vimrc<CR>
nnoremap <leader>n :set number!<CR>
nnoremap <leader><space> :nohlsearch<CR>
inoremap jk <Esc>l
