#!/usr/bin/env bash

# exit
alias e='exit'

# clear screen
alias clr='clear'

# disk and memory usage
alias df='df -h'
alias free='free -h'

# general process searching
alias psg='ps aux | grep -v grep | grep -i -e VSZ -e'

# git
alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gl='git log --oneline'
# lazygit
alias lg='lazygit'

# docker
alias d='docker'
alias dc='docker compose'

# tree
for i in {1..5}; do
  alias "tree$i"="tree -alC -L $i -I '.git'"
done

# nvidia-smi
alias gpuinfo="nvidia-smi"
alias nvismi="nvidia-smi"
