alias e='exit'

# cd
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# clear screen
alias clr='clear'

# disk and memory usage
alias df='df -h'
alias free='free -h'

# git
alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gl='git log --oneline'
alias lg='lazygit'

# docker
alias d='docker'
alias dc='docker compose'

# tree
for i in {1..5}; do
  alias "tree$i"="tree -alC -L $i -I '.git'"
done

# yazi
alias yy="yazi"
